# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  :sparkles: Yeah, you just opened your first pull request. Now, we will look at it... :sparkles:

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  :tada: Everything looked fine and your first first pull request was merged! Congratulation! :tada:
